### PR TITLE
Merge/tidepool

### PR DESCRIPTION
**Pull request by BigFab**
PR for after having merged our master code with Tidepool's

This branch is being tested by Hydrophone, Shoreline and Tide-whisperer.

Once those tests are done and success, this PR can be merged. Then, the 3 services would need to be updated so they reference go-common from 'master' branch and not 'merge/tidepool'.

### CODE REVIEW

**Comment by BigFab** [comment]
Did you notice that Travis is running tests even though the .travis.yml does not contain any execution of any script? Would Travis automatically run "go test" by default?
I did not find anything on the web regarding this automatic run.
@ydrisR @CedricPerotto

**Comment by BigFab** [comment]
Let's test it with shoreline, hydrophone and tide-whisperer before merging

**Comment by BigFab** [comment]
Tests with hydrophone are done and OK: Hydrophone can run with this branch of go-common

**Comment by BigFab** [comment]
Tests with shoreline are done and OK

**Comment by BigFab** [comment]
Tests with Tide-whisperer are done and OK

**The PR can now be merged and all 3 dependencies be updated to no more reflect the WIP branch**

**Review by CedricPerotto — APPROVED** [review]
LGTM

**Pull request merged**
